#!/bin/sh
BASEDIR=`dirname $0`

CLASSPATH=$BASEDIR

for i in $BASEDIR/lib/*.jar
do 
CLASSPATH=$CLASSPATH:$i 
done

echo exec java \
	-XstartOnFirstThread \
	-classpath $CLASSPATH \
	-Djava.library.path=$BASEDIR/swt \
	net.eclipseforum.id3tagman.ID3TagManGUI

java \
	-XstartOnFirstThread \
	-cp $CLASSPATH \
	-Dapp.root=$BASEDIR \
	net.eclipseforum.id3tagman.ID3TagManGUI

